/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        /* ── Light Mode Defaults ── */
        "surface-container-high": "var(--surface-container-high)",
        "background": "var(--background)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "on-error-container": "var(--on-error-container)",
        "outline-variant": "var(--outline-variant)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-dim": "var(--surface-dim)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary": "var(--on-secondary)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "primary": "var(--primary)",
        "tertiary": "var(--tertiary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-variant": "var(--surface-variant)",
        "on-tertiary": "var(--on-tertiary)",
        "on-surface": "var(--on-surface)",
        "outline": "var(--outline)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "error-container": "var(--error-container)",
        "primary-container": "var(--primary-container)",
        "secondary": "var(--secondary)",
        "on-error": "var(--on-error)",
        "surface": "var(--surface)",
        "surface-tint": "var(--surface-tint)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-primary": "var(--on-primary)",
        "error": "var(--error)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-container": "var(--secondary-container)",
        "surface-bright": "var(--surface-bright)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-background": "var(--on-background)",
        "surface-container": "var(--surface-container)",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        md: "16px",
        lg: "32px",
        unit: "4px",
        sm: "8px",
        gutter: "24px",
        xl: "64px",
        xs: "4px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "500" }],
      },
      animation: {
        'spin-slow': 'spin 8s linear infinite',
      },
    },
  },
  plugins: [],
};
