version: '3.8'
services:
  mongodb:
    image: mongo:8.0
    container_name: mern_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    # Using redis:7.4 or latest since 8.0/8.8 might not be standard on dockerhub yet, but I'll specify latest and let it pull the newest available.
    image: redis:latest
    container_name: mern_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
