import {makeFeatureClient} from '../../../../shared/featureData';
import {useEffect,useState} from 'react';
import api from '../../lib/axios';
const client=makeFeatureClient(api);
export default function TaskTools({task,canEdit,onChange}){
 const [comments,setComments]=useState([]),[children,setChildren]=useState([]),[comment,setComment]=useState(''),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setComments([]);setChildren([]);Promise.all([client.all('/comments/task/'+task._id,{},c.signal),client.all('/tasks',{workspaceId:task.workspaceId,parentTaskId:task._id},c.signal)]).then(([a,b])=>{if(!c.signal.aborted){setComments(a);setChildren(b);}}).catch(e=>{if(!c.signal.aborted)setError(e.response?.data?.message||'Could not load task details');});return()=>c.abort();},[task._id,task.workspaceId,revision]);
 const act=async fn=>{setBusy(true);setError('');try{await fn();setRevision(x=>x+1);onChange?.();}catch(e){setError(e.response?.data?.message||e.message);}finally{setBusy(false);}};
 const upload=file=>act(async()=>{const form=new FormData();form.append('workspaceId',task.workspaceId);form.append('file',file);const {data}=await api.post('/upload',form);await api.put('/tasks/'+task._id,{attachments:[...(task.attachments||[]),data]});});
 const download=assetId=>act(async()=>{const {data}=await api.get('/upload/'+assetId+'/download');window.location.assign(data.url);});
 return <section className="space-y-4 border-t border-outline-variant pt-4"><h3 className="font-semibold">Task details</h3>{error&&<p role="alert">{error}</p>}
 <div><h4>Subtasks</h4>{(task.subtasks||[]).map((item,index)=><label className="flex gap-2" key={item._id||index}><input type="checkbox" checked={item.isCompleted} disabled={!canEdit||busy} onChange={()=>act(()=>api.put('/tasks/'+task._id,{subtasks:task.subtasks.map((entry,i)=>i===index?{...entry,isCompleted:!entry.isCompleted}:entry)}))}/>{item.title}</label>)}{children.map(child=><label className="flex gap-2" key={child._id}><input type="checkbox" disabled={!canEdit||busy} checked={child.status==='completed'} onChange={()=>act(()=>api.put('/tasks/'+child._id,{status:child.status==='completed'?'pending':'completed'}))}/>{child.title}</label>)}{canEdit&&<form onSubmit={e=>{e.preventDefault();act(async()=>{await api.post('/tasks',{title,parentTaskId:task._id,workspaceId:task.workspaceId});setTitle('');});}} className="flex gap-2"><input aria-label="Subtask title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} className="border border-outline-variant bg-transparent p-2" required/><button disabled={busy}>Add subtask</button></form>}</div>
 <div><h4>Attachments</h4>{(task.attachments||[]).map((a,i)=><div className="flex gap-3" key={a.assetId||i}><button disabled={!a.assetId||busy} onClick={()=>download(a.assetId)}>{a.name}</button>{canEdit&&<button disabled={busy} onClick={()=>act(()=>api.put('/tasks/'+task._id,{attachments:task.attachments.filter((_,index)=>index!==i)}))}>Remove</button>}</div>)}{canEdit&&<label>Upload JPEG, PNG or PDF<input type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy} onChange={e=>{if(e.target.files[0])upload(e.target.files[0]);e.target.value='';}}/></label>}</div>
 <div><h4>Comments</h4>{comments.map(c=><article className="py-2" key={c._id}><p>{c.user?.name||'Former member'} / {new Date(c.createdAt).toLocaleString()}</p><p>{c.content}</p>{canEdit&&<button disabled={busy} onClick={()=>act(()=>api.delete('/comments/'+c._id))}>Delete comment</button>}</article>)}{canEdit&&<form onSubmit={e=>{e.preventDefault();act(async()=>{await api.post('/comments/task/'+task._id,{content:comment});setComment('');});}}><textarea aria-label="Comment" className="w-full p-2 border border-outline-variant bg-transparent" value={comment} onChange={e=>setComment(e.target.value)} maxLength={10000} required/><button disabled={busy}>Post comment</button></form>}</div>
 {canEdit&&<button disabled={busy} onClick={()=>act(()=>api.post('/tasks/'+task._id+'/duplicate'))}>Duplicate task</button>}
 </section>;
}
