import {makeFeatureClient} from '../../../../shared/featureData';
import React,{useEffect,useState} from 'react';
import {View,Text,TextInput,TouchableOpacity,Linking} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import api from '../../services/api';
import {useTheme} from '../../context/ThemeContext';
const client=makeFeatureClient(api);
export default function TaskTools({task,canEdit,onChange}){
 const {colors}=useTheme(),[comments,setComments]=useState([]),[children,setChildren]=useState([]),[comment,setComment]=useState(''),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setComments([]);setChildren([]);Promise.all([client.all('/comments/task/'+task._id,{},c.signal),client.all('/tasks',{workspaceId:task.workspaceId,parentTaskId:task._id},c.signal)]).then(([a,b])=>{if(!c.signal.aborted){setComments(a);setChildren(b);}}).catch(e=>{if(!c.signal.aborted)setError(e.response?.data?.message||'Could not load task details');});return()=>c.abort();},[task._id,task.workspaceId,revision]);
 const act=async fn=>{setBusy(true);setError('');try{await fn();setRevision(x=>x+1);onChange?.();}catch(e){setError(e.response?.data?.message||e.message);}finally{setBusy(false);}};
 const upload=()=>act(async()=>{const result=await DocumentPicker.getDocumentAsync({type:['image/jpeg','image/png','application/pdf'],copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];const form=new FormData();form.append('workspaceId',task.workspaceId);form.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType});const {data}=await api.post('/upload',form,{headers:{'Content-Type':'multipart/form-data'}});await api.put('/tasks/'+task._id,{attachments:[...(task.attachments||[]),data]});});
 const text={color:colors.onSurface},input={padding:12,borderWidth:1,borderColor:colors.outlineVariant,color:colors.onSurface};
 const button=(label,fn)=> <TouchableOpacity accessibilityRole="button" disabled={busy} onPress={fn} style={{paddingVertical:10}}><Text style={{color:colors.primary}}>{label}</Text></TouchableOpacity>;
 return <View style={{gap:12,borderTopWidth:1,borderColor:colors.outlineVariant,paddingTop:16}}><Text style={{...text,fontWeight:'700'}}>Task details</Text>{error&&<Text accessibilityRole="alert" style={{color:colors.error}}>{error}</Text>}
 <Text style={text}>Subtasks</Text>{(task.subtasks||[]).map((item,index)=><TouchableOpacity key={item._id||index} accessibilityRole="checkbox" accessibilityState={{checked:item.isCompleted}} disabled={!canEdit||busy} onPress={()=>act(()=>api.put('/tasks/'+task._id,{subtasks:task.subtasks.map((entry,i)=>i===index?{...entry,isCompleted:!entry.isCompleted}:entry)}))}><Text style={text}>{item.isCompleted?'Completed:':'Pending:'} {item.title}</Text></TouchableOpacity>)}{children.map(child=><TouchableOpacity key={child._id} accessibilityRole="checkbox" accessibilityState={{checked:child.status==='completed'}} disabled={!canEdit||busy} onPress={()=>act(()=>api.put('/tasks/'+child._id,{status:child.status==='completed'?'pending':'completed'}))}><Text style={text}>{child.status==='completed'?'Completed:':'Pending:'} {child.title}</Text></TouchableOpacity>)}{canEdit&&<View><TextInput accessibilityLabel="Subtask title" style={input} value={title} onChangeText={setTitle} maxLength={200}/>{button('Add subtask',()=>act(async()=>{await api.post('/tasks',{title,parentTaskId:task._id,workspaceId:task.workspaceId});setTitle('');}))}</View>}
 <Text style={text}>Attachments</Text>{(task.attachments||[]).map((a,i)=><View key={a.assetId||i}>{a.assetId?button(a.name,()=>act(async()=>{const {data}=await api.get('/upload/'+a.assetId+'/download');await Linking.openURL(data.url);})):<Text style={text}>{a.name} / Legacy attachment requires reupload</Text>}{canEdit&&button('Remove attachment',()=>act(()=>api.put('/tasks/'+task._id,{attachments:task.attachments.filter((_,index)=>index!==i)})))}</View>)}{canEdit&&button('Upload JPEG, PNG or PDF',upload)}
 <Text style={text}>Comments</Text>{comments.map(c=><View key={c._id}><Text style={text}>{c.user?.name||'Former member'} / {new Date(c.createdAt).toLocaleString()}</Text><Text style={text}>{c.content}</Text>{canEdit&&button('Delete comment',()=>act(()=>api.delete('/comments/'+c._id)))}</View>)}{canEdit&&<View><TextInput accessibilityLabel="Comment" style={input} multiline value={comment} onChangeText={setComment} maxLength={10000}/>{button('Post comment',()=>act(async()=>{await api.post('/comments/task/'+task._id,{content:comment});setComment('');}))}</View>}{canEdit&&button('Duplicate task',()=>act(()=>api.post('/tasks/'+task._id+'/duplicate')))}
 </View>;
}
